//! winmm.dll proxy: every export of the real `System32\winmm.dll` (same names and ordinals, table in
//! `exports.txt`) is a 4-instruction asm stub generated by `build.rs`. A stub jumps through `EVT_PROXY_TABLE`;
//! the first call of each export resolves it here (`LoadLibraryW(<System32>\winmm.dll)` + `GetProcAddress`).
//! Argument registers (rcx, rdx, r8, r9, xmm0-3) and the caller's stack are preserved, so this works for every
//! signature without knowing it. No work at all is done in DllMain for the proxy.

#![allow(static_mut_refs)]

use std::sync::atomic::{AtomicUsize, Ordering};
use windows_sys::Win32::Foundation::HMODULE;
use windows_sys::Win32::System::LibraryLoader::{GetProcAddress, LoadLibraryW};
use windows_sys::Win32::System::SystemInformation::GetSystemDirectoryW;

include!(concat!(env!("OUT_DIR"), "/proxy_stubs.rs"));

/// Resolved addresses, read by the asm stubs (`sym` operand).
pub static mut EVT_PROXY_TABLE: [usize; EXPORT_COUNT] = [0; EXPORT_COUNT];

static REAL: AtomicUsize = AtomicUsize::new(0);

fn real_winmm() -> HMODULE {
    let h = REAL.load(Ordering::Acquire);
    if h != 0 {
        return h as HMODULE;
    }
    let mut buf = [0u16; 520];
    let n = unsafe { GetSystemDirectoryW(buf.as_mut_ptr(), 500) } as usize;
    if n == 0 || n >= 500 {
        return std::ptr::null_mut();
    }
    let mut path: Vec<u16> = buf[..n].to_vec();
    path.extend("\\winmm.dll".encode_utf16());
    path.push(0);
    let m = unsafe { LoadLibraryW(path.as_ptr()) };
    if !m.is_null() {
        REAL.store(m as usize, Ordering::Release);
    }
    m
}

extern "C" fn evt_proxy_missing() -> usize {
    0
}

/// Called by the asm stubs with the export index; returns the real function (never 0).
pub extern "C" fn evt_proxy_resolve(i: u32) -> usize {
    let i = i as usize;
    if i >= EXPORT_COUNT {
        return evt_proxy_missing as *const () as usize;
    }
    let m = real_winmm();
    let (ord, name) = EXPORTS[i];
    let f = if m.is_null() {
        None
    } else if name.is_empty() {
        unsafe { GetProcAddress(m, ord as usize as *const u8) }
    } else {
        let c: Vec<u8> = name.bytes().chain(std::iter::once(0)).collect();
        unsafe { GetProcAddress(m, c.as_ptr()) }
    };
    match f {
        Some(p) => {
            let a = p as usize;
            unsafe { std::ptr::write_volatile(std::ptr::addr_of_mut!(EVT_PROXY_TABLE[i]), a) };
            a
        }
        None => {
            crate::error!("proxy: cannot resolve winmm export #{ord} {name:?} (real winmm loaded: {})", !m.is_null());
            evt_proxy_missing as *const () as usize
        }
    }
}
