//! Table index for data deltas (module `mods`, [`super::merge`]): which game file holds a table
//! (`character/chara_param`), which T2B entry name its rows use, which column is the row key and the index of every
//! named column. Generated by `build.rs` from `schemas/<folder>/*.toml` (T2B tables only; `schemas/README.md`), so
//! the loader needs no schema files at run time.

use std::collections::HashMap;
use std::sync::OnceLock;

/// The generated index text (one line per table, see `build.rs` `table_index`).
pub const INDEX_TEXT: &str = include_str!(concat!(env!("OUT_DIR"), "/table_index.tsv"));

#[derive(Debug, Clone, PartialEq)]
pub struct TableInfo {
    /// `folder/id` (the `table` of a delta).
    pub id: String,
    /// T2B entry name of the rows (`CHARA_PARAM_INFO`).
    pub list: String,
    /// Value index of the row key, when the schema names one.
    pub key: Option<usize>,
    /// File globs (`data/common/gamedata/character/chara_param_*.cfg.bin`; `{placeholder}` = any text).
    pub files: Vec<String>,
    /// Column name -> value index.
    pub columns: HashMap<String, usize>,
}

impl TableInfo {
    pub fn column(&self, name: &str) -> Option<usize> {
        self.columns.get(name).copied()
    }
}

/// Parse index text (tab-separated lines: id, list, key, globs `;`, `index:name` `,`).
pub fn parse_index(text: &str) -> HashMap<String, TableInfo> {
    let mut m = HashMap::new();
    for line in text.lines().filter(|l| !l.trim().is_empty()) {
        let f: Vec<&str> = line.split('\t').collect();
        if f.len() < 5 {
            continue;
        }
        let columns = f[4]
            .split(',')
            .filter_map(|c| {
                let (i, n) = c.split_once(':')?;
                Some((n.to_string(), i.parse::<usize>().ok()?))
            })
            .collect();
        let info = TableInfo {
            id: f[0].to_string(),
            list: f[1].to_string(),
            key: f[2].parse().ok(),
            files: f[3].split(';').filter(|s| !s.is_empty()).map(str::to_string).collect(),
            columns,
        };
        m.entry(info.id.clone()).or_insert(info);
    }
    m
}

/// The built-in index (parsed on first use).
pub fn index() -> &'static HashMap<String, TableInfo> {
    static IDX: OnceLock<HashMap<String, TableInfo>> = OnceLock::new();
    IDX.get_or_init(|| parse_index(INDEX_TEXT))
}

/// `name` without its version suffix (`chara_param_1.03.66.00.cfg.bin` -> `chara_param.cfg.bin`), lowercase.
fn unversioned(key: &str) -> String {
    let k = key.to_ascii_lowercase();
    let (dir, name) = k.rsplit_once('/').unwrap_or(("", &k));
    let (stem, ext) = match name.find('.') {
        Some(_) if name.ends_with(".cfg.bin") => {
            let e = name.len() - ".cfg.bin".len();
            (&name[..e], &name[e..])
        }
        Some(i) => (&name[..i], &name[i..]),
        None => (name, ""),
    };
    let base = match stem.rsplit_once('_') {
        Some((b, v)) if !v.is_empty() && v.split('.').count() >= 2 && v.split('.').all(|p| !p.is_empty() && p.bytes().all(|c| c.is_ascii_digit())) => b,
        _ => stem,
    };
    format!("{dir}/{base}{ext}")
}

/// The live game file of `t` among `keys` (cpk_list keys, `data/...` lowercase): every key matching one of its globs
/// (placeholders = `*`; an unversioned glob also matches the versioned names); they must all be versions of ONE
/// file (else the table spans several files: per map / language), and the highest version wins.
pub fn resolve_file<'a>(t: &TableInfo, keys: impl Iterator<Item = &'a str>) -> Result<String, String> {
    let pats: Vec<String> = t
        .files
        .iter()
        .flat_map(|g| {
            let p = vr_gamefiles::pattern::normalize_pattern(&g.to_ascii_lowercase());
            let alt = p.strip_suffix(".cfg.bin").filter(|s| !s.ends_with('*')).map(|s| format!("{s}_*.cfg.bin"));
            std::iter::once(p).chain(alt)
        })
        .collect();
    if pats.is_empty() {
        return Err(format!("table `{}` has no file pattern", t.id));
    }
    let hits: Vec<&str> = keys.filter(|k| pats.iter().any(|p| vr_gamefiles::pattern::wildcard(p, k))).collect();
    if hits.is_empty() {
        return Err(format!("no game file matches {}", t.files.join(", ")));
    }
    let mut hits = hits;
    let mut groups: Vec<String> = hits.iter().map(|k| unversioned(k)).collect();
    groups.sort();
    groups.dedup();
    if groups.len() > 1 {
        // `x_*.cfg.bin` is the versioned `x.cfg.bin`: `x_table_config_*.cfg.bin` is another file
        let named: Vec<String> = pats
            .iter()
            .filter_map(|p| p.strip_suffix("_*.cfg.bin").filter(|s| !s.contains('*')).map(|s| format!("{s}.cfg.bin")))
            .collect();
        if groups.iter().any(|g| named.contains(g)) {
            hits.retain(|k| named.contains(&unversioned(k)));
            groups.retain(|g| named.contains(g));
        }
    }
    if groups.len() > 1 {
        let shown: Vec<&str> = groups.iter().take(3).map(String::as_str).collect();
        return Err(format!(
            "table `{}` spans {} files ({}{}): deltas need a table of one file (ship the file in files/)",
            t.id,
            groups.len(),
            shown.join(", "),
            if groups.len() > 3 { ", ..." } else { "" }
        ));
    }
    let best = hits
        .iter()
        .max_by(|a, b| {
            let na = a.rsplit('/').next().unwrap_or(a);
            let nb = b.rsplit('/').next().unwrap_or(b);
            vr_gamefiles::pattern::version_key(na).cmp(&vr_gamefiles::pattern::version_key(nb)).then(b.cmp(a))
        })
        .copied()
        .unwrap_or_default();
    Ok(best.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn built_in_index_has_chara_param() {
        let t = index().get("character/chara_param").expect("chara_param in the generated index");
        assert_eq!(t.list, "CHARA_PARAM_INFO");
        assert_eq!(t.key, Some(0));
        assert_eq!(t.column("element"), Some(2));
        assert!(t.files[0].contains("chara_param_"));
        assert!(index().len() > 1000, "{}", index().len());
    }

    #[test]
    fn parse_and_resolve() {
        let idx = parse_index(
            "a/t\tT_INFO\t0\tdata/common/gamedata/a/t_*.cfg.bin\t0:id,1:x,2:y\n\
             a/u\tU_INFO\t\tdata/common/gamedata/a/u.cfg.bin\t0:id\n\
             a/m\tM_INFO\t0\tdata/common/gamedata/map/{map}/{map}_m.cfg.bin\t\n",
        );
        let t = &idx["a/t"];
        assert_eq!((t.key, t.column("y"), t.column("z")), (Some(0), Some(2), None));
        assert_eq!(idx["a/u"].key, None);
        let keys = [
            "data/common/gamedata/a/t_1.02.00.00.cfg.bin",
            "data/common/gamedata/a/t_1.10.00.00.cfg.bin",
            "data/common/gamedata/a/t_1.9.00.00.cfg.bin",
            "data/common/gamedata/a/u_1.00.00.00.cfg.bin",
            "data/common/gamedata/map/w01/w01_m.cfg.bin",
            "data/common/gamedata/map/w02/w02_m.cfg.bin",
        ];
        assert_eq!(resolve_file(t, keys.iter().copied()).unwrap(), "data/common/gamedata/a/t_1.10.00.00.cfg.bin");
        // unversioned pattern matches the versioned name
        assert_eq!(resolve_file(&idx["a/u"], keys.iter().copied()).unwrap(), "data/common/gamedata/a/u_1.00.00.00.cfg.bin");
        // per-map table: several files
        assert!(resolve_file(&idx["a/m"], keys.iter().copied()).unwrap_err().contains("spans 2 files"));
        assert!(resolve_file(t, ["data/x.cfg.bin"].into_iter()).unwrap_err().contains("no game file"));
        // `t_*` is the versioned t.cfg.bin, not t_table_config
        let more = ["data/common/gamedata/a/t_1.00.00.00.cfg.bin", "data/common/gamedata/a/t_table_config_0.00.00.00.cfg.bin"];
        assert_eq!(resolve_file(t, more.iter().copied()).unwrap(), more[0]);
        assert_eq!(unversioned("data/a/T_1.02.00.00.cfg.bin"), "data/a/t.cfg.bin");
        assert_eq!(unversioned("data/a/t_x.cfg.bin"), "data/a/t_x.cfg.bin");
    }
}
